#!/usr/bin/env bash

wget https://cdn.local.epitech.eu/userprofil/yoann.cayron.bmp
wget https://cdn.local.epitech.eu/userprofil/adam.lardeux.bmp
wget https://cdn.local.epitech.eu/userprofil/alexandre.frizzo.bmp
wget https://cdn.local.epitech.eu/userprofil/alexis.senechal.bmp
wget https://cdn.local.epitech.eu/userprofil/antoine.ferry.bmp
wget https://cdn.local.epitech.eu/userprofil/antoine.orion.bmp
wget https://cdn.local.epitech.eu/userprofil/arthur.elhoussine.bmp
wget https://cdn.local.epitech.eu/userprofil/arthur.lang.bmp
wget https://cdn.local.epitech.eu/userprofil/axel.denise.bmp
wget https://cdn.local.epitech.eu/userprofil/axel.millot.bmp
wget https://cdn.local.epitech.eu/userprofil/carl.lebrun.bmp
wget https://cdn.local.epitech.eu/userprofil/cedric.legendre.bmp
wget https://cdn.local.epitech.eu/userprofil/corentin.martin.bmp
wget https://cdn.local.epitech.eu/userprofil/david.leroy.bmp
wget https://cdn.local.epitech.eu/userprofil/davy.henry.bmp
wget https://cdn.local.epitech.eu/userprofil/dorian.nicolas.bmp
wget https://cdn.local.epitech.eu/userprofil/dylan.santos.bmp
wget https://cdn.local.epitech.eu/userprofil/elian.nicaise.bmp
wget https://cdn.local.epitech.eu/userprofil/elmer.lechaudel.bmp
wget https://cdn.local.epitech.eu/userprofil/erwan.cheviron.bmp
wget https://cdn.local.epitech.eu/userprofil/gabriel.colson.bmp
wget https://cdn.local.epitech.eu/userprofil/guillaume.assfeld.bmp
wget https://cdn.local.epitech.eu/userprofil/haroutioun.sargsyan.bmp
wget https://cdn.local.epitech.eu/userprofil/jonathan.lemoine.bmp
wget https://cdn.local.epitech.eu/userprofil/jules.esteves-duarte.bmp
wget https://cdn.local.epitech.eu/userprofil/julie.pecci.bmp
wget https://cdn.local.epitech.eu/userprofil/kylian.maugue.bmp
wget https://cdn.local.epitech.eu/userprofil/lise.knoll.bmp
wget https://cdn.local.epitech.eu/userprofil/loan.boye.bmp
wget https://cdn.local.epitech.eu/userprofil/lucas.hemmerle.bmp
wget https://cdn.local.epitech.eu/userprofil/lucas.tabis.bmp
wget https://cdn.local.epitech.eu/userprofil/mathieu.keller.bmp
wget https://cdn.local.epitech.eu/userprofil/matteo.volpi.bmp
wget https://cdn.local.epitech.eu/userprofil/moussa.taddrarat.bmp
wget https://cdn.local.epitech.eu/userprofil/nathan.malingre.bmp
wget https://cdn.local.epitech.eu/userprofil/nicolas.zona.bmp
wget https://cdn.local.epitech.eu/userprofil/paul.brunner.bmp
wget https://cdn.local.epitech.eu/userprofil/paulin.flammang.bmp
wget https://cdn.local.epitech.eu/userprofil/pierre.bolze.bmp
wget https://cdn.local.epitech.eu/userprofil/quentin.leuenberger.bmp
wget https://cdn.local.epitech.eu/userprofil/quentin.sanchez.bmp
wget https://cdn.local.epitech.eu/userprofil/raphael.ozdoba.bmp
wget https://cdn.local.epitech.eu/userprofil/remi.vuillemin.bmp
wget https://cdn.local.epitech.eu/userprofil/tanguy.raeymaekers.bmp
wget https://cdn.local.epitech.eu/userprofil/theo.steffanetti.bmp
wget https://cdn.local.epitech.eu/userprofil/thomas.lopvet.bmp
wget https://cdn.local.epitech.eu/userprofil/vincent.meurie-ichai.bmp
